version: '3.5'

services:
  harvey-ims-web:
    build:
      args:
        BUILD_MODE: --prod
        CONFIG_MODE: --configuration=uat
    ports:
      - "4100:80"

  harvey-purchase-order-web:
    build:
      args:
        BUILD_MODE: --prod
        CONFIG_MODE: --configuration=uat
    ports:
      - "4200:80"

  harvey-retail-web:
    build:
      args:
        BUILD_MODE: --prod
        CONFIG_MODE: --configuration=uat
    ports:
      - "4400:80"

  harvey-promotion-web:
    build:
      args:
        BUILD_MODE: --prod
        CONFIG_MODE: --configuration=uat
    ports:
      - "4300:80"