export const SchemaNames = {
    migration: 'Migrations',
    appSetting: 'AppSettings',
    category: 'Categories',
    product: 'Products',
    variant: 'Variants',
    customer: 'Customers',
    user: 'Users',
    order: 'Orders',
    orderItem: 'OrderItems',
    pendingSale: 'PendingSales',
    pendingSaleItem: 'PendingSaleItems',
    cashingUp: 'CashingUps',
    tender: 'Tenders',
    promotion: 'Promotions',
    orderPromotion: 'OrderPromotions',
    orderItemPromotion: 'OrderItemPromotions',
    barCode: 'BarCodes',
    saleTarget: 'SaleTargets',
    salesAchieved: 'SalesAchieved',
    orderPayment: 'OrderPayments',
    paymentMethod: 'PaymentMethods',
    defaultPaymentMethod: 'DefaultPaymentMethods',
    location: 'Locations'
};
